project:
  type: website
  output-dir: docs

# Meta
description-meta: "Juebin's Personal Page"
author-meta: "Juebin Zeng, PhD in Finance"

website:
  title: "Juebin Zeng"
  image: "files/images/professional_photo.jpg"
  description: "Juebin's Personal Page"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About
        href: pages/about/           
      - text: Posts
        href: pages/posts/
      - text: Research
        href: pages/research/
#      - text: Teaching # Comment the Teaching part out to remove the Teaching page
#        href: pages/teaching/
      - text: Presentations
        href: pages/presentations/                   
#      - text: Group   # Comment the Group part out to remove the Group page
#        href: pages/people/

    right: 
      - text: CV
        href: CV/CV_academic_Juebin Zeng.pdf
  
  page-navigation: true
  
  page-footer: 
    left: "[Juebin Zeng](https://github.com/jzen95) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on Quarto"
  
  search:
    location: navbar
    type: textbox
  

  draft-mode: unlinked
  
  repo-url: https://github.com/jzen95/jzen.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://jzen.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    theme-toggle: true
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/jzen\.github\.io'
    include-before-body: "files/includes/_pathbar.qmd"

