project:
  type: website
  output-dir: docs

# Meta
description-meta: "Juebin's Personal Page"
author-meta: "Juebin Zeng, PhD in Finance"

website:
  title: "Juebin Zeng"
  image: "https://quarto.org/quarto.png"
  description: "Juebin's Personal Page"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About
        href: about.qmd           
      - text: Research
        menu:
          - text: List of Publications
            href: publications.qmd
          - text: Selected Papers
            href: posts.qmd#category=paper
      - text: Projects
        href: projects.qmd                                
#      - text: Teaching # Comment the Teaching part out to remove the Teaching page
#        href: teaching.qmd
      - text: Presentations
        href: presentations.qmd                   
#      - text: Group   # Comment the Group part out to remove the Group page
#        href: people.qmd

    right: 
      - text: CV
        href: files/nsf-biosketch.pdf
      - icon: github
        href: https://github.com/drganghe/quarto-academic-website-template
        target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app
        target: _blank      
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Juebin Zeng](https://github.com/jzen95) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Build on Quarto"
    right:  
      - icon: github
        href: https://github.com/jzen95/jzen.github.io
        target: _blank
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/jzen95/jzen.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://jzen.github.io"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

